# languageCode = "en-us"
IsMultiLingual = true
DefaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
title = "Sven Oloff"
description = "Violoncello"
baseurl = "http://www.sven-oloff.de/"
theme = "startbootstrap-clean-blog"
layoutDir = "custom/layouts"
staticDir = ["custom/static", "static"]
publishDir = "docs"
googleAnalytics = "UA-117483988-1"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Violoncello"
  Author = "Sven Oloff"
  email = ""
  postSummariesFrontPage = 4 #Number of post summaries to show on front page, comment out to allow default(4)
  Copyright = ""
  
[[params.footer]]
  title = "Impressum"
  url = "/impressum/"
[[params.footer]]
  title = "Contact"
  url = "/contact/"

[taxonomies]
  tag = "tags"
  category = "categories"

[Languages] 
[Languages.de]
weight = 1
[[Languages.de.menu.main]]
  name = "home"
  url = "/de/"
  weight = 1
[[Languages.de.menu.main]]
  name = "Musik"
  url = "/de/music/"
  weight = 2
[[Languages.de.menu.main]]
  name = "Bilder"
  url = "/de/photo/"
  weight = 3
[[Languages.de.menu.main]]
  name = "Archiv"
  url = "/de/arch/"
  weight = 4
[[Languages.de.menu.main]] 
  name = "Am Rand"  
  url = "/de/misc/"
  weight = 5


[Languages.en]
weight = 3
[Languages.en.params]
[[Languages.en.menu.main]]
  name = "Home"
  url = "/en/"
  weight = 1
[[Languages.en.menu.main]]
  name = "Music"
  url = "/en/music/"
  weight = 2
[[Languages.en.menu.main]]
  name = "Photos"
  url = "/en/photo/"
  weight = 3
[[Languages.en.menu.main]]
  name = "Archive"
  url = "/en/arch/"
  weight = 4
[[Languages.en.menu.main]] 
  name = "Side Note"  
  url = "/en/misc/"
  weight = 5

[Languages.fr]
weight = 2
[Languages.fr.params]
[[Languages.fr.menu.main]]
  name = "Entree"
  url = "/fr/"
  weight = 1
[[Languages.fr.menu.main]]
  name = "Music"
  url = "/fr/music/"
  weight = 2
[[Languages.fr.menu.main]]
  name = "Photos"
  url = "/fr/photo/"
  weight = 3
[[Languages.fr.menu.main]]
  name = "Archive"
  url = "/fr/arch/"
  weight = 4
[[Languages.fr.menu.main]] 
  name = "Side Note"  
  url = "/fr/misc/"
  weight = 5
