languageCode = "de-de"
title = "Sven Oloff"
baseurl = "http://localhost:1313/"

[params]
  DateForm = "2. January 2006"
  Description = "Beschreibung der Seite"
  Author = "Sven Oloff"
  email = "sven-oloff@gmx.de"
  Ganalytics = "XX-00000000-0"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -260
[[menu.main]]
  name = "Musik"
  url = "/music/"
  weight = -240
[[menu.main]]
  name = "Archiv"
  url = "/archive/"
  weight = -200
[[menu.main]]
  name = "Foto"
  url = "/foto/"
  weight = -220
[[menu.main]] 
  name = "Am Rand"
  url = "/misc/"
  weight = -180
